(eval-when-compile (add-to-list 'load-path  (expand-file-name "~/.emacs.d/site-lisp/")) (require 'compile-dwim ) )

(defun joseph_compile_current_el_outside()
  (let ((command (format  " emacs  -batch    -l %s -f batch-byte-compile %s "
                          (expand-file-name "~/.emacs.d/site-lisp/joseph/joseph_byte_compile_include.el")
                          (buffer-file-name))))
    (with-current-buffer (get-buffer-create "*joseph_compile_current_el*")
      (insert (shell-command-to-string command)))
    (switch-to-buffer (get-buffer-create "*joseph_compile_current_el*"))))

(setq compile-dwim-alist
      `((visual-basic (or (name . "\\.\\(frm\\|bas\\|cls\\|vba\\)$")
                          (mode . visual-basic-mode))
                      (run-vb) (run-vb))
        (erlang (or (name . "\\.erl$")
                  (mode . erlang-mode))
                (erlang-dired-emake) "erl  \"%f\"")
        (perl (or (name . "\\.pl$")
                  (mode . cperl-mode))
              "%i -wc \"%f\"" "%i \"%f\"")
        (c    (or (name . "\\.c$")
                  (mode . c-mode))
              "gcc -o %n %f" "./%n")
        ;; (c    (or (name . "\\.c$")
        ;;           (mode . c-mode))
        ;;       ("gcc -o %n %f" "gcc -g -o %n %f") ("./%n" "cint %f") "%n")
        (c++  (or (name . "\\.cpp$")
                  (mode . c++-mode))
              ("g++ -o %n %f" "g++ -g -o %n %f") "./%n" "%n")
        (java (or (name . "\\.java$")
                  (mode . java-mode))
              "javac %f" "java %n" "%n.class")
        (python (or (name . "\\.py$")
                    (mode . python-mode))
                "%i %f" "%i %f")
        (javascript (or (name . "\\.js$")
                        (mode . javascript-mode))
                    "smjs -f %f" "smjs -f %f")
        (tex   (or (name . "\\.tex$")
                   (name . "\\.ltx$")
                   (mode . tex-mode)
                   (mode . latex-mode))
               "latex %f" "latex %f" "%n.dvi")
        (texinfo (name . "\\.texi$")
                 (makeinfo-buffer) (makeinfo-buffer) "%.info")
        (sh    (or (name . "\\.sh$")
                   (mode . sh-mode))
               "%i ./%f" "%i ./%f")
        (f99   (name . "\\.f90$")
               "f90 %f -o %n" "./%n" "%n")
        (f77   (name . "\\.[Ff]$")
               "f77 %f -o %n" "./%n" "%n")
        (php   (or (name . "\\.php$")
                   (mode . php-mode))
               "php %f" "php %f")
        (elisp (or (name . "\\.el$")
                   (mode . emacs-lisp-mode)
                   (mode . lisp-interaction-mode))
               (joseph_compile_current_el_outside)
               (emacs-lisp-byte-compile) "%fc"))
      );;;; eval-after-load compile-dwim
(provide 'joseph-compile-dwim)
;;; joseph-compile-dwim.el ends here
