                  ("@" allout-resolve-xref)
                  ("=c" allout-copy-exposed-to-buffer)
                  ("=i" allout-indented-exposed-to-buffer)
                  ("=t" allout-latexify-exposed)
                  ("=p" allout-flatten-exposed-to-buffer)))
  )
;;;_.  Gnu Emacs 24 版的allout
(when (string-match "GNU Emacs 24" (emacs-version))
  (setq-default allout-prefixed-keybindings
                '(("[(control ?n)]" allout-next-visible-heading)
                  ("[(control ?p)]" allout-previous-visible-heading)
                  ("[(control ?u)]" allout-up-current-level)
                  ("[(control ?f)]" allout-forward-current-level)
                  ("[(control ?b)]" allout-backward-current-level)
                  ("[(control ?a)]" allout-beginning-of-current-entry)
                  ("[(control ?e)]" allout-end-of-entry)
                  ("[(control ?i)]" allout-show-children)
                  ("[(control ?s)]" allout-show-current-subtree)
                  ("[?s]" allout-show-current-subtree)
                  ("[(control ?t)]" allout-toggle-current-subtree-exposure)
                  ;; Let user customize if they want to preempt describe-prefix-bindings ^h use.
                  ;;    ("[(control ?h)]" allout-hide-current-subtree)
                  ("[?h]" allout-hide-current-subtree)
                  ("[(control ?h)]" allout-hide-current-subtree)
                  ("[?H]" allout-hide-bodies)
                  ("[(control ?w)]" allout-hide-bodies)
                  ("[(control ?o)]" allout-show-current-entry)
                  ("[?o]" allout-show-current-entry)
                  ("[?!]" allout-show-all)
                  ("[(control ?a)]" allout-show-all)
                  ("[?x]" allout-toggle-current-subtree-encryption)
                  ("[? ]" allout-open-sibtopic)

                  ("[?.]" allout-open-subtopic)
                  ("[(control ?.)]" allout-open-subtopic)

                  ("[?,]" allout-open-supertopic)
                  ("[(control ?,)]" allout-open-supertopic)
                  ("[?']" allout-shift-in)
                  ("[?>]" allout-shift-in)
                  ("[?<]" allout-shift-out)
                  ("[(control ?m)]" allout-rebullet-topic)
                  ("[?*]" allout-rebullet-current-heading)
                  ("[?#]" allout-number-siblings)
                  ("[(control ?k)]" allout-kill-topic)
                  ("[(meta ?k)]" allout-copy-topic-as-kill)
                  ("[?@]" allout-resolve-xref)
                  ("[?=?c]" allout-copy-exposed-to-buffer)
                  ("[?=?i]" allout-indented-exposed-to-buffer)
                  ("[?=?t]" allout-latexify-exposed)
                  ("[?=?p]" allout-flatten-exposed-to-buffer)
                  )
                )
  (allout-compose-and-institute-keymap)
  )
;;;_. common config
